# Generated by Django 4.2.13 on 2024-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
