# Generated by Django 4.2.13 on 2024-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_remove_problem_code_solution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
